name: Build

on:
  release:
    types:
      - published
      # - created
      # - edited
      # - prereleased

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: lucienzhangzl/website
        tags: latest
        tag_with_ref: true
